[package]
name = "specs_hierarchy"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]

[dependencies]
hibitset = "0.5"
specs = { version = "0.10", git = "https://github.com/slide-rs/specs" }
shred = "0.7.0-alpha2"
shrev = "0.8"
shred-derive = "0.5.0-alpha1"
